#ifndef MINIMAL_SUPERLOOP_CONFIG_H
#define MINIMAL_SUPERLOOP_CONFIG_H

#include "app_config.h"

#define MINIMAL_TAU1_PERIOD_US 10000ULL
#define MINIMAL_TAU2_PERIOD_US 50000ULL

#if (EXPERIMENT_MODE == EXPERIMENT_MINIMAL_SUPERLOOP_PROFILE) || \
    (EXPERIMENT_MODE == EXPERIMENT_SUPERLOOP_CHECKS_PROFILE)
  /* Dedicated two-task workloads; integrated-task values stay unchanged. */
  #if WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U50
    #define MINIMAL_TAU1_WORKLOAD_US 2500ULL
    #define MINIMAL_TAU2_WORKLOAD_US 12500ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U50"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 50U
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U65
    #define MINIMAL_TAU1_WORKLOAD_US 3250ULL
    #define MINIMAL_TAU2_WORKLOAD_US 16250ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U65"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 65U
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U80
    #define MINIMAL_TAU1_WORKLOAD_US 4000ULL
    #define MINIMAL_TAU2_WORKLOAD_US 20000ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U80"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 80U
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U90
    #define MINIMAL_TAU1_WORKLOAD_US 4500ULL
    #define MINIMAL_TAU2_WORKLOAD_US 22500ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U90"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 90U
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U95
    #define MINIMAL_TAU1_WORKLOAD_US 4750ULL
    #define MINIMAL_TAU2_WORKLOAD_US 23750ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U95"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 95U
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U100
    #define MINIMAL_TAU1_WORKLOAD_US 5000ULL
    #define MINIMAL_TAU2_WORKLOAD_US 25000ULL
    #define MINIMAL_WORKLOAD_SCENARIO_NAME "U100"
    #define MINIMAL_WORKLOAD_UTILIZATION_PERCENT 100U
  #else
    #error "Minimal Superloop profile supports U50, U65, U80, U90, U95, and U100 only"
  #endif
#endif

#endif /* MINIMAL_SUPERLOOP_CONFIG_H */
