#ifndef WORKLOAD_CONFIG_H
#define WORKLOAD_CONFIG_H

#include "app_config.h"

/* Physical sensor periods. */
#define TAU1_PERIOD_US 100000ULL
#define TAU2_PERIOD_US 2000000ULL
#define TAU1_PERIOD_MS 100U
#define TAU2_PERIOD_MS 2000U

#if (INTEGRATED_SYNTH_TASK_COUNT < 2) || (INTEGRATED_SYNTH_TASK_COUNT > 3)
  #error "INTEGRATED_SYNTH_TASK_COUNT must be 2 or 3"
#endif

#if INTEGRATED_SYNTH_TASK_COUNT == 3
  #define ENABLE_SYNTH_CAMERA 1
#else
  #define ENABLE_SYNTH_CAMERA 0
#endif

/* Integrated synthetic-task periods. */
#define TAU_IMU_PERIOD_US 10000ULL
#define TAU_IMU_PERIOD_MS 10U
#define TAU_LIDAR_PERIOD_US 50000ULL
#define TAU_LIDAR_PERIOD_MS 50U
#define TAU_CAMERA_PERIOD_US 200000ULL
#define TAU_CAMERA_PERIOD_MS 200U

#if WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U50
  #define TAU_IMU_WORKLOAD_US 1667ULL
  #define TAU_LIDAR_WORKLOAD_US 11111ULL
  #define TAU_CAMERA_WORKLOAD_US 22222ULL
  #define WORKLOAD_SCENARIO_NAME "U50"
  #define WORKLOAD_UTILIZATION_PERCENT 50U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U65
  #define TAU_IMU_WORKLOAD_US 2167ULL
  #define TAU_LIDAR_WORKLOAD_US 14444ULL
  #define TAU_CAMERA_WORKLOAD_US 28889ULL
  #define WORKLOAD_SCENARIO_NAME "U65"
  #define WORKLOAD_UTILIZATION_PERCENT 65U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U75
  #define TAU_IMU_WORKLOAD_US 2500ULL
  #define TAU_LIDAR_WORKLOAD_US 16667ULL
  #define TAU_CAMERA_WORKLOAD_US 33332ULL
  #define WORKLOAD_SCENARIO_NAME "U75"
  #define WORKLOAD_UTILIZATION_PERCENT 75U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U80
  #define TAU_IMU_WORKLOAD_US 2667ULL
  #define TAU_LIDAR_WORKLOAD_US 17778ULL
  #define TAU_CAMERA_WORKLOAD_US 35556ULL
  #define WORKLOAD_SCENARIO_NAME "U80"
  #define WORKLOAD_UTILIZATION_PERCENT 80U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U90
  #define TAU_IMU_WORKLOAD_US 3000ULL
  #define TAU_LIDAR_WORKLOAD_US 20000ULL
  #define TAU_CAMERA_WORKLOAD_US 40000ULL
  #define WORKLOAD_SCENARIO_NAME "U90"
  #define WORKLOAD_UTILIZATION_PERCENT 90U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U95
  #define TAU_IMU_WORKLOAD_US 3167ULL
  #define TAU_LIDAR_WORKLOAD_US 21111ULL
  #define TAU_CAMERA_WORKLOAD_US 42222ULL
  #define WORKLOAD_SCENARIO_NAME "U95"
  #define WORKLOAD_UTILIZATION_PERCENT 95U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U100
  #define TAU_IMU_WORKLOAD_US 3333ULL
  #define TAU_LIDAR_WORKLOAD_US 22222ULL
  #define TAU_CAMERA_WORKLOAD_US 44444ULL
  #define WORKLOAD_SCENARIO_NAME "U100"
  #define WORKLOAD_UTILIZATION_PERCENT 100U
#elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U110
  #define TAU_IMU_WORKLOAD_US 3667ULL
  #define TAU_LIDAR_WORKLOAD_US 24444ULL
  #define TAU_CAMERA_WORKLOAD_US 48889ULL
  #define WORKLOAD_SCENARIO_NAME "U110"
  #define WORKLOAD_UTILIZATION_PERCENT 110U
#else
  #error "Unsupported WORKLOAD_SCENARIO"
#endif

#if (EXPERIMENT_MODE == EXPERIMENT_INTEGRATED) && \
    (INTEGRATED_SYNTH_TASK_COUNT == 2)
  /* Re-normalize the remaining IMU/LiDAR 3:4 workload split to target U. */
  #if WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U50
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 2143ULL
    #define TAU_LIDAR_WORKLOAD_US 14285ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U65
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 2786ULL
    #define TAU_LIDAR_WORKLOAD_US 18570ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U75
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 3214ULL
    #define TAU_LIDAR_WORKLOAD_US 21430ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U80
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 3429ULL
    #define TAU_LIDAR_WORKLOAD_US 22855ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U90
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 3857ULL
    #define TAU_LIDAR_WORKLOAD_US 25715ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U95
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 4071ULL
    #define TAU_LIDAR_WORKLOAD_US 27145ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U100
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 4286ULL
    #define TAU_LIDAR_WORKLOAD_US 28570ULL
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U110
    #undef TAU_IMU_WORKLOAD_US
    #undef TAU_LIDAR_WORKLOAD_US
    #define TAU_IMU_WORKLOAD_US 4714ULL
    #define TAU_LIDAR_WORKLOAD_US 31430ULL
  #endif
#endif

#define UTIL_X10000_BASE \
  ((ENABLE_SYNTH_IMU * TAU_IMU_WORKLOAD_US * 10000ULL / TAU_IMU_PERIOD_US) + \
   (ENABLE_SYNTH_LIDAR * TAU_LIDAR_WORKLOAD_US * 10000ULL / TAU_LIDAR_PERIOD_US))

#if ENABLE_SYNTH_CAMERA
  #define UTIL_X10000 \
    (UTIL_X10000_BASE + \
     (TAU_CAMERA_WORKLOAD_US * 10000ULL / TAU_CAMERA_PERIOD_US))
#else
  #define UTIL_X10000 UTIL_X10000_BASE
#endif

#define ACTIVE_SYNTH_TASK_COUNT (ENABLE_SYNTH_IMU + ENABLE_SYNTH_LIDAR + ENABLE_SYNTH_CAMERA + ENABLE_SYNTH_CONTROL)
#define PROFILE_WINDOW_MS (PROFILE_WINDOW_US / 1000ULL)
#define DEBUG_PERIOD_US 1000000ULL

#if (SCHED_ALGO != SCHED_ALGO_SUPERLOOP) && \
    (SCHED_ALGO != SCHED_ALGO_CHUNKED_EDF)
  #error "Unsupported scheduler algorithm"
#endif

#if EDF_CHUNK_US == 0ULL
  #error "EDF_CHUNK_US must be greater than zero"
#endif

#if SCHED_ALGO == SCHED_ALGO_CHUNKED_EDF
  #define SCHED_ALGO_NAME "CHUNKED_EDF"
  #define SCHED_CSV_CHUNK_US EDF_CHUNK_US
#else
  #define SCHED_ALGO_NAME "SUPERLOOP"
  #define SCHED_CSV_CHUNK_US 0ULL
#endif

#if (EXPERIMENT_MODE == EXPERIMENT_SUPERLOOP_SCALABILITY_CLEAN) || \
    (EXPERIMENT_MODE == EXPERIMENT_SUPERLOOP_SCALABILITY_CHECKS)
  #if (SCALABILITY_TASK_COUNT < 2) || (SCALABILITY_TASK_COUNT > 4)
    #error "SCALABILITY_TASK_COUNT must be 2, 3, or 4"
  #endif

  #define SCALABILITY_TAU1_PERIOD_US 10000ULL
  #define SCALABILITY_TAU2_PERIOD_US 20000ULL
  #define SCALABILITY_TAU3_PERIOD_US 50000ULL
  #define SCALABILITY_TAU4_PERIOD_US 100000ULL

  #if WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U65
    #define SCALABILITY_WORKLOAD_SCENARIO_NAME "U65"
    #define SCALABILITY_WORKLOAD_UTILIZATION_PERCENT 65U
    #if SCALABILITY_TASK_COUNT == 2
      #define SCALABILITY_TAU1_WORKLOAD_US 3250ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 6500ULL
    #elif SCALABILITY_TASK_COUNT == 3
      #define SCALABILITY_TAU1_WORKLOAD_US 2167ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 4334ULL
      #define SCALABILITY_TAU3_WORKLOAD_US 10830ULL
    #else
      #define SCALABILITY_TAU1_WORKLOAD_US 1625ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 3250ULL
      #define SCALABILITY_TAU3_WORKLOAD_US 8125ULL
      #define SCALABILITY_TAU4_WORKLOAD_US 16250ULL
    #endif
  #elif WORKLOAD_SCENARIO == WORKLOAD_SCENARIO_U90
    #define SCALABILITY_WORKLOAD_SCENARIO_NAME "U90"
    #define SCALABILITY_WORKLOAD_UTILIZATION_PERCENT 90U
    #if SCALABILITY_TASK_COUNT == 2
      #define SCALABILITY_TAU1_WORKLOAD_US 4500ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 9000ULL
    #elif SCALABILITY_TASK_COUNT == 3
      #define SCALABILITY_TAU1_WORKLOAD_US 3000ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 6000ULL
      #define SCALABILITY_TAU3_WORKLOAD_US 15000ULL
    #else
      #define SCALABILITY_TAU1_WORKLOAD_US 2250ULL
      #define SCALABILITY_TAU2_WORKLOAD_US 4500ULL
      #define SCALABILITY_TAU3_WORKLOAD_US 11250ULL
      #define SCALABILITY_TAU4_WORKLOAD_US 22500ULL
    #endif
  #else
    #error "Superloop scalability profiles support U65 and U90 only"
  #endif
#endif

#endif /* WORKLOAD_CONFIG_H */
